### ISSUE TITLE
建议：支持 DSL Api 构建

### ISSUE THREAD

**Issue by vvVenom** [XuQK/KDTabLayout#2]
既然用上了 Kotlin 那怎么能少 dsl 形式呢，现在的创建方式感觉太过繁琐了，可以的话建议设计更加简洁的 api，就像 https://github.com/afollestad/recyclical

**Comment by XuQK** [comment]
也就Adapter的构建适合转为DSL API，转换前后区别不打，目前无太大必要。

**Comment by SaltedFish-Extreme** [comment]
这我直接推荐BRV了 https://github.com/liangjingkanji/BRV/
