### ISSUE TITLE
初始化选项卡名称数量必须大于0问题

### ISSUE THREAD

**Issue by qq570026938** [XuQK/KDTabLayout#3]
现在初始化时title必须有值才行，可以优化一下，初始化时title集合可以传空集合，在获取到具体数据后在更新具体的值吗

**Comment by XuQK** [comment]
可以是可以这么改，但是觉得没啥必要，你完全可以获取到具体数据后再进行初始化，我自己也是这么做的

**Comment by qq570026938** [comment]
> 可以是可以这么改，但是觉得没啥必要，你完全可以获取到具体数据后再进行初始化，我自己也是这么做的

我现在也是这么用的，但总感觉不太好适应，获取数据后在初始化一大堆东西很不舒服，应该在开始就先初始化了，之后在刷新数据就行了
你demo中也有个随机添加的功能，这挺好，但是初始化必须有值就不太好了，如果硬是用的话，就是我初始化给个空字符串集合，然后获取到数据后刷新在tab.init()一下
还有就是如果写在获取到数据后在初始化，是不是还得额外判断初始化状况，不能多次初始化吧，建议改一下，那就顺滑了，跟使用官方的一样，可以先没有值，获取到数据刷新就行了
