### ISSUE TITLE
修改Tab文本的字体

### ISSUE THREAD

**Issue by AndroidYeshao** [XuQK/KDTabLayout#6]
可以修改Tab文本的字体吗，自己下载的ttf字体

**Comment by XuQK** [comment]
可以参考库中定义的KDSizeMorphingTextTab类自己定义自己需要的tab，在合适的实际，设置paint的typeface为你需要的字体即可。

**Comment by AndroidYeshao** [comment]
没有修改成功，不过找到了一个属性可以设置为粗体，这样也行，谢谢

**Comment by lmick002** [comment]
@XuQK do you have an example of changing the font to a custom font? Thanks
