### ISSUE TITLE
以前的 MagicIndicatorFragmen 里有一个FragmentContainerHelper() 可以不绑定ViewPager 即可使用的 KDTabLayout 有此功能嘛

### ISSUE THREAD

**Issue by zhangjianzhu** [XuQK/KDTabLayout#9]
val helper = FragmentContainerHelper()
val commonNavigator = CommonNavigator(appCompatActivity)
mi_home.navigator = commonNavigator
helper.attachMagicIndicator(mi_home)

**Comment by XuQK** [comment]
没有必要，配合ViewPager足够了，如果需要的话可以自己copy他那个类出来用，相关接口都有。

**Comment by XuQK** [comment]
没有必要，配合ViewPager足够了，如果需要的话可以自己copy他那个类出来用，相关接口都有。
